config/routes.rb
BjjReview::Application.routes.draw do

  resources :reviews

  devise_for :user, :controllers => { :sessions => 'user_session',
                                      :registrations => 'user_registration'}

  devise_scope :user do
    get "sign_in", :to => "user_session#new"
    get "sign_out", :to => "devise/sessions#destroy"
    get "sign_up_new", :to => "user_registration#new"
  end

  root :to => "home#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :reviews

  attr_accessible :answer, :question
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :title, :url, :context, :reviewer_id, :presence => true
  belongs_to :user
  before_create :setState
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:question].blank? }, :allow_destroy => true
  attr_accessible :questions_attributes, :reviewer_id, :url, :title, :overall_comments, :suggested_drills, :state, :context


  private
  def setState
    self.state = "Queued"
  end


end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, :rank, :academy, :yrs_training, :presence => true
  has_many :reviews
  has_and_belongs_to_many :roles

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :academy, :rank, :yrs_training


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index

    if (current_user)
    @reviews = current_user.reviews

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
    else
      redirect_to root_path
    end
    
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    if (current_user)
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
        else
      redirect_to root_path
    end

  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    if (current_user)
    @review = Review.find(params[:id])
    else
      redirect_to root_path
    end

  end

  # POST /reviews
  # POST /reviews.json
  def create

    puts(params[:review])
    @review = Review.new(params[:review])

    @review.user = current_user

    respond_to do |format|
      if @review.save
        ReviewMailer.review_requested(@review).deliver
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    review_attrs = params[:review]

    respond_to do |format|
      if @review.update_attributes(params[:review])

        if (review_attrs[:questions_attributes])
          review_attrs[:questions_attributes].each do |index,question|
            if (question[:answer])
              @question = Question.find(question[:id])
              @question.update_attributes(question)
            end
          end
        end

        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :ok }
    end
  end
end

app/controllers/user_registration_controller.rb
class UserRegistrationController < Devise::RegistrationsController

  def index
    super
  end

  def create
    build_resource

#    resource.roles.build({:role => "Student"})
    student_role = Role.find_all_by_role "Student"
    resource.roles << student_role

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => redirect_location(resource_name, resource)
      else
        set_flash_message :notice, :inactive_signed_up, :reason => inactive_reason(resource) if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords(resource)
      respond_with_navigational(resource) { render_with_scope :new }
    end

  end

  def destroy
    super
  end

  def new
    super
  end

  def edit
    super
  end

end

app/controllers/user_session_controller.rb
class UserSessionController < Devise::SessionsController

  def index
    super
  end

  def create

    resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)

    respond_with resource, :location => reviews_url
  end

  def destroy
    super
  end

  def new
    super
  end

  def edit
    super
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
#  def link_to_remove_fields(name, f)
#    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
#  end

#  def link_to_add_fields(name, f, association)
#    new_object = f.object.class.reflect_on_association(association).klass.new
#    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
#      render(association.to_s.singularize + "_fields", :f => builder)
#    end
#    puts(fields.to_s)
#    link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
#  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def parseYoutube(review)
      parsedURL = URI.parse(review.url)
      youtubeId = ""
      if (parsedURL.host = "www.youtube.com")
        if (parsedURL.query != nil)
          queryParams = parsedURL.query
          if (queryParams =~ /&/ )
            queryParams = parsedURL.query.split("&")[0]
          end
         youtubeId = queryParams.split("=")[1]
        else
        youtubeId = parsedURL.path.split("/")[1]
        end
      end
      return youtubeId
  end

  def getAllReviewers()
    return User.joins(:roles).where('roles.role' => "Reviewer")
  end

end

app/views/home/index.html.erb
<h1>BJJ VIDEO REVIEW</h1>
<% if current_user %>
Hi <%=  current_user.first_name %><br></br>
<%= link_to "Go To Reviews", reviews_url   %>
<%  end %>
<br></br>
<% if !current_user %>
<%= link_to "LOGIN", sign_in_path %>
<%= link_to "SIGN UP", sign_up_new_path %>
<%  end %>
<%= link_to "LOGOUT", sign_out_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bjj Video Review</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%#= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/_edit_reviewer_form.html.erb
<%= nested_form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2><%= @review.title %><br /></h2>
  </div>
<%
      youtubeId = parseYoutube(@review)
%>

<iframe width="420" height="315" src="http://www.youtube.com/embed/<%= youtubeId %>?rel=0" frameborder="0" allowfullscreen></iframe>
<br></br><br></br>
<div class="field">
  <%= f.fields_for :questions do |builder| %>
  <%# debugger %>
  <%= builder.label builder.object.question%>
<%#= builder.label :answer %><br></br>
  <%= builder.text_area :answer, :size => "40x3" %>
  <br></br><br></br>
  <% end %>
</div>

<div class="field">
    <%= f.label :overall_comments %><br />
    <%= f.text_area :overall_comments, :size => "40x10" %>
</div>

<div class="field">
    <%= f.label :suggested_drills %><br />
    <%= f.text_area :suggested_drills, :size => "40x10"  %>
</div>

<div class="field">
  <%= f.radio_button :state, "In Progress" %>
  <%= f.label :state, "In Progress", :value => "In Progress"%>
  <%= f.radio_button :state, "Complete" %>
  <%= f.label :state, "Complete", :value => "Complete"%>
</div>

<div class="actions">
    <%= f.submit params[:action] == "new" ? "Request Review" : "Update Review", :class => 'button' %>
  </div>
<% end %>

app/views/reviews/_edit_student_form.html.erb
<%= nested_form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Youtube URL:"%><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label "Context (Please provide background info for this video including how to identify you):" %><br />
    <%= f.text_area :context, :size => "40x10"  %>
  </div>
  <%= f.label "Select A Reviewer:" %><br></br>

  <%

  reviewers = getAllReviewers()

     for i in reviewers
       selected = false;
        if (i.id == @review.reviewer_id)
          selected = true;
        end
  %>
<div class="field">
  <%= f.radio_button :reviewer_id, i.id, :checked => selected %>
  <%= f.label :reviewer_id, i.first_name + " " + i.last_name, :value => i.id%>
</div>
<% end %>
<%
      youtubeId = parseYoutube(@review)
%>

<iframe width="420" height="315" src="http://www.youtube.com/embed/<%= youtubeId %>?rel=0" frameborder="0" allowfullscreen></iframe>
<br></br><br></br>

<div class="field">
  <%= f.fields_for :questions do |builder| %>
  <%= builder.text_field :question %>
  <%= builder.link_to_remove "Remove Question"%>
  <% end %>
  <p><%= f.link_to_add("Add Question", :questions)  %></p>
</div>
  <div class="actions">
    <%= f.submit "Update Review", :class => 'button' %>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<%= nested_form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <% @allUsers = User.all

  # Is there a faster or better way of getting all reviewers from the Users?

     reviewers = Array.new
     for user in @allUsers
       for role in user.roles
         if (role.role == "Reviewer" )
           reviewers.push user
         end
       end
     end

     for i in reviewers
       selected = false;
        if (params[:action] == "edit" && i.id == @review.reviewer_id)
          selected = true;
        end
  %>
<div class="field">
  <%= f.radio_button :reviewer_id, i.id, :checked => selected %>
  <%= f.label :reviewer_id, i.first_name + " " + i.last_name, :value => i.id%>
</div>
<% end %>
<% if (params[:action] == "edit") %>
  <%

   # This logic is used in multiple places.  Where is the logical place to store it as a function?

      parsedURL = URI.parse(@review.url)
      if (parsedURL.host = "www.youtube.com")
        if (parsedURL.query != nil)
          queryParams = parsedURL.query
          if (queryParams =~ /&/ )
            queryParams = parsedURL.query.split("&")[0]
          end
         youtubeId = queryParams.split("=")[1]
        else
        youtubeId = parsedURL.path.split("/")[1]
        end
      end
%>

<iframe width="420" height="315" src="http://www.youtube.com/embed/<%= youtubeId %>?rel=0" frameborder="0" allowfullscreen></iframe>
<br></br><br></br>
<% end %>
<div class="field">
  <%= f.fields_for :questions do |builder| %>
  <%= builder.text_field :question %>
  <%= builder.link_to_remove "Remove Question"%>
  <% end %>
  <p><%= f.link_to_add("Add Question", :questions)  %></p>
</div>
  <div class="actions">
    <%= f.submit params[:action] == "new" ? "Request Review" : "Update Review", :class => 'button' %>
  </div>
<% end %>

app/views/reviews/_new_form.html.erb
<%= nested_form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Youtube URL:" %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label "Context (please provide background info for this video including how to identify you):" %><br />
    <%= f.text_area :context, :size => "40x10"  %>
  </div>
  <%= f.label "Select A Reviewer:" %><br></br>
  <%

     reviewers = getAllReviewers()

     for i in reviewers
  %>
<div class="field">
  <%= f.radio_button :reviewer_id, i.id %>
  <%= f.label :reviewer_id, i.first_name + " " + i.last_name, :value => i.id%>
</div>
<% end %>
<div class="field">
  <%= f.fields_for :questions do |builder| %>
  <%= builder.text_field :question %>
  <%= builder.link_to_remove "Remove Question"%>
  <% end %>
  <p><%= f.link_to_add("Add Question", :questions)  %></p>
</div>
  <div class="actions">
    <%= f.submit "Request Review", :class => 'button' %>
  </div>
<% end %>

app/views/reviews/_question_fields.html.erb
<div class="field">
<p>
   <%= f.label :question, "Question" %><br></br>
   <%= f.text_field :question %>
   <%= f.check_box :_destroy %>
   <%= f.label :_destroy, "Remove" %>
  </p>
</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%
for i in current_user.roles
  if (i.role == "Reviewer")
    reviewer = true;
  elsif (i.role == "Student")
    student = true;
  elsif (i.role == "Admin")
    admin = true;
  end
end
%>

<!-- What is the best way to approach different edit forms for different users? -->
<% if reviewer %>
  <%= render 'edit_reviewer_form' %>
<% elsif student %>
  <%= render 'edit_student_form' %>
<% end %>
<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<%
   a = current_user.roles
   for i in current_user.roles
     if (i.role == "Admin")
       admin = true
     elsif (i.role == "Student")
       student = true
     elsif (i.role == "Reviewer")
       reviewer = true
     end
   end

%>

<% if admin %>
<h1>ADMIN</h1>
<hr></hr>
<% end %>

<% if reviewer %>

<h1>Review Summary For <%= current_user.first_name%> <%=  current_user.last_name %></h1>

<% @newlyRequested = Review.where(:reviewer_id => current_user.id) %>

<table>
  <tr>
    <th align="left">Title</th>
    <th align="left">Status</th>
    <th align="left">Student</th>
    <th></th>
    <th></th>
  </tr>

<% @newlyRequested.each do |newReq| %>
  <tr>
    <td><%= newReq.title %></td>
    <td><%= newReq.state %></td>
    <td><%= newReq.user.first_name + " " + newReq.user.last_name %></td>
    <td><%= link_to 'Do Review', edit_review_path(newReq) %></td>
  </tr>
<% end %>
</table>
<% end %>

<% if student %>

<% if current_user.reviews.count > 0 %>
<h1>Reviews for <%= current_user.first_name%> <%=  current_user.last_name %> </h1>

<table>
  <tr>
    <th align="left">Title</th>
    <th>Review Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.title %></td>
    <td><%= review.state %></td>
    <td><% if review.state == "Complete"%> <%= link_to 'Show', review %> <%end%></td>
    <td><% if review.state == "Queued"%> <%= link_to 'Edit', edit_review_path(review) %><%end%></td>
    <td><%= link_to 'Delete', review, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br/>
<% else %>
<br>You haven't requested any reviews yet</br><br></br>
<% end %>
<%= link_to 'New Review', new_review_path %>
<br></br>
<br></br>
<%= link_to "LOGOUT", sign_out_path %>

<% end %>

app/views/reviews/new.html.erb
<h1>New Video Review</h1>

<%= render 'new_form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @review.title %>
</p>

<p>
  <b>Review Status:</b>
  <%= @review.state %>
</p>

  <%
      puts("URL: " + @review.url.to_s)
      parsedURL = URI.parse(@review.url)
      if (parsedURL.host = "www.youtube.com")
        if (parsedURL.query != nil)
          queryParams = parsedURL.query
          if (queryParams =~ /&/ )
            queryParams = parsedURL.query.split("&")[0]
          end
         youtubeId = queryParams.split("=")[1]
        else
        youtubeId = parsedURL.path.split("/")[1]
        end
      end
%>

<iframe width="420" height="315" src="http://www.youtube.com/embed/<%= youtubeId %>?rel=0" frameborder="0" allowfullscreen></iframe>
<br></br><br></br>
<b>Video Reviewer:</b>
<% u = User.find(@review.reviewer_id) %>
<%= u.first_name + " " + u.last_name %>
<br></br><br></br>
<%
for i in @review.questions
%>
<b><%= i.question %></b>
<br>Ans: <%= i.answer %></br>
<br></br><br></br>
<%end%>

<b>Overall Comments:</b><br></br>
<%= @review.overall_comments %><br></br>
<br></br>
<b>Suggested Drills:</b><br></br>
<%= @review.suggested_drills %><br></br>
<br></br>
<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>
<br></br>
<%= link_to "LOGOUT", sign_out_path %>

app/views/user_registration/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
  <%= f.password_field :current_password %></div>

  <div><%= f.submit "Update" %></div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete %>.</p>

<%= link_to "Back", :back %>

app/views/user_registration/new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>


  <%= devise_error_messages! %>

  <div><%= f.label :first_name %><br />
  <%= f.text_field :first_name %></div>

  <div><%= f.label :last_name %><br />
  <%= f.text_field :last_name %></div>

  <div><%= f.label :academy %><br />
  <%= f.text_field :academy %></div>

  <div><%= f.label :rank %><br />
  <%= f.text_field :rank %></div>

  <div><%= f.label :yrs_training %><br />
  <%= f.text_field :yrs_training %></div>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>


  <div><%= f.submit "Sign up" %></div>
<% end %>

<%= render :partial => "devise/shared/links" %>

app/views/user_session/new.html.erb
<h2>Sign in</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" %></div>
<% end %>

<%= render :partial => "devise/shared/links" %>